### ISSUE TITLE
After submitting the document game freezes

### ISSUE THREAD

**Issue by Javier-Diez** [apoiat/ESX_Documents#1]
I pressed L, wrote random words and dates. Pressed submit, game freezes and I need to restart resource. I attach screenshot of f8 console as the only strange thing I see is the "WTFFFFF!".
![Screenshot_225](https://user-images.githubusercontent.com/35200252/58587965-e7436080-825e-11e9-8b0b-07eefe0de4d0.png)

**Comment by apoiat** [comment]
Hmm the wtf part is some debug code left behind, i removed it dont worry about. Gonna run some tests. Did you import the .sql file without problems?

**Comment by Javier-Diez** [comment]
Yes, no problems

**Comment by apoiat** [comment]
nui://esx_documents-master/html/script.js:246
it could be nui problem with the folder name. Switch folder name to esx_documents as instructed and change your server.cfg to start the resource with the correct name. report back

**Comment by Javier-Diez** [comment]
Ok let me check

**Comment by apoiat** [comment]
I made a fresh install and seems to be working fine following the steps i provided. Also updated the repo to fix some font issues people were having. I suggest you get the new one if you are using english characters

**Comment by UKRP1** [comment]
Hi, seen your updates. I added this script to my server, exactly as instructed.  The GUI Freezes on screen after clicking submit

**Comment by apoiat** [comment]
I tested this and the behavior you are both describing happens if you don't name the resource folder esx_documents. Please both make sure your folder name is as this. Also download the repo again and overwrite previous folder. no need to import the sql again

**Comment by Javier-Diez** [comment]
Issue fixed. Download latest release, renamed ESX_Documents to esx_documents. Works perfectly. Excellent Release.
