### ISSUE TITLE
enhancement - support of radio buttons  and checkboxes 

### ISSUE THREAD

**Issue by TanguyOrtegat** [apoiat/ESX_Documents#10]
Would be great to make support for radiobuttons and checkboxes

**Comment by apoiat** [comment]
Also on my to-do list!

**Comment by TanguyOrtegat** [comment]
> here a little help:

		if (this.type == "checkbox") {
			_html += "<div>";
			_html += "<p class=\"input_label\">" + this.label + "</p>";
			if(this.checked){
				_html += "<input class=\"inputcheckbox\" type=\"checkbox\" id=\"" + this.elementid + "\"/checked><label for=\"" + this.elementid + "\">" + this.value + "</label>";
			} else {
				_html += "<input class=\"inputcheckbox\" type=\"checkbox\" id=\"" + this.elementid + "\"/><label for=\"" + this.elementid + "\">" + this.value + "</label>";
			}
			_html += "</div>"
		}		
		if (this.type == "date") {
			_html += "<p class=\"input_label\">" + this.label + "</p>";
			_html += "<input type=\"date\" id=\"" + this.elementid + "\" value=\"" + this.value + "\"/>";
		}		
		
		if (this.type == "number") {
			_html += "<p class=\"input_label\">" + this.label + "</p>";
			_html += "<input type=\"number\" id=\"" + this.elementid + "\" value=\"" + this.value + "\"/>";
		}
