### ISSUE TITLE
Job documents not showing for "mechanic"

### ISSUE THREAD

**Issue by sebastiannl** [apoiat/ESX_Documents#15]
["mechanic"] = {
        {
          headerTitle = "COTIZACIÓN PARA MODIFICACIONES",
          headerSubtitle = "Documento con los detalles y valores para la modificación de un vehículo.",
          elements = {
            { label = "NOMBRE DE CLIENTE", type = "input", value = "", can_be_emtpy = false },
            { label = "APELLIDO DE CLIENTE", type = "input", value = "", can_be_emtpy = false },
            { label = "FECHA DE EMISIÓN", type = "input", value = "", can_be_empty = false },
            { label = "DETALLE", type = "textarea", value = "En este recuadro deben especificar las piezas y el valor de cada una a modo de cotización para un cliente. Recuerde hacerlo con orden y que sea entendible.", can_be_emtpy = false },
          }
        },
        {
          headerTitle = "FACTURA MECÁNICA",
          headerSubtitle = "Documento que menciona el trabajo hecho por un mecánico y sus detalles.",
          elements = {
            { label = "NOMBRE DE CLIENTE", type = "input", value = "", can_be_emtpy = false },
            { label = "APELLIDO DE CLIENTE", type = "input", value = "", can_be_emtpy = false },
            { label = "FECHA DE EMISIÓN", type = "input", value = "", can_be_empty = false },
            { label = "DETALLE", type = "textarea", value = "El mecánico debe especificar detalladamente qué trabajo hizo y los valores de este. Abarca reparaciones, modificaciones, limpieza, remolque, etc. Recuerde hacerlo de manera ordenada y entendible.", can_be_emtpy = false },
          }
        }

**Comment by apoiat** [comment]
There is no entry for mechanic in initial script
