### ISSUE TITLE
document adding

### ISSUE THREAD

**Issue by mrfunbeard** [apoiat/ESX_Documents#3]
There is no obvious place to add new and custom documents. Can you explain to me where the documents that are already implemented are and tell me where to add new ones? which file/script do I edit

**Comment by apoiat** [comment]
Unfortunately there was no one single obvious place i could place them (like the config file) because of the different languages i tried to implement. So for English, you will have to edit locale/en.lua for new forms and html/language_en.js if you want to change static text that appears on forms.

**Comment by mrfunbeard** [comment]
I apologize for not checking there before posting this! That’s the only place I didn’t check lol. I really appreciate it! Your script is amazing!
