### ISSUE TITLE
Physical Database for Documents

### ISSUE THREAD

**Issue by mrfunbeard** [apoiat/ESX_Documents#4]
Is there any way to implement a physical database for the documents. Such as say a filing cabinet in the police station to put arrest reports or a filing cabinet in the mechanic shop to put receipts. Would be extremely useful for roleplay. (And I know this isn’t an issue I just wasn’t sure where else to post it)

**Comment by apoiat** [comment]
Sorry for the late reply, been quite busy. I really like this idea and find it interesting. I'll have a look at it and get back

**Comment by mrfunbeard** [comment]
If there is anything I can do to help just let me know. I can do my best to work with you on it (don’t have a crazy amount of coding experience)

**Comment by Briixain** [comment]
Is there a way to allow other than police? I have Highway Patrol and FBI and I would like them to be able to use the "L" button as well.

**Comment by mrfunbeard** [comment]
Yes. Write it in in the locale file

**Comment by Briixain** [comment]
The one location I didn't look in because I made a presumption. LOL. Thank
you so much for getting back to me.  Love the work!
