### ISSUE TITLE
support for double jobs

### ISSUE THREAD

**Issue by TanguyOrtegat** [apoiat/ESX_Documents#6]
i ll post some issues, but each in separate thread.
First of all this is a great script, you do save me a lot of time in rp writing reports and so on but in the first 5 minutes of testing i do have found some issues. The first one, is supporting servers that have  double jobs. Would be great when opening a menu, that we first can choose what job (first or second and then open the menus.

**Comment by apoiat** [comment]
I understand the need behind it, and i'm 100% with you on it. But i do not have an environment available for testing this and getting or setting one up will take up a lot of time. If anyone can help with this one i will be grateful.

**Comment by TanguyOrtegat** [comment]
I did have a small fix, i can show up all the job related things for both jobs, but on the paper, it will always be the first job that takes advantage. 
here is how i did partially fix that issue:
`function OpenNewJobFormMenu()
    ClearMenu()
    PlayerData = ESX.GetPlayerData()
    if DOCUMENT_FORMS[PlayerData.job.name] ~= nil  then

        for i=1, #DOCUMENT_FORMS[PlayerData.job.name], 1 do
            Menu.addButton(DOCUMENT_FORMS[PlayerData.job.name][i].headerTitle, "CreateNewForm", DOCUMENT_FORMS[PlayerData.job.name][i])
        end    
    end
	if DOCUMENT_FORMS[PlayerData.second_job.name] ~= nil then
		for i=1, #DOCUMENT_FORMS[PlayerData.second_job.name], 1 do
            Menu.addButton(DOCUMENT_FORMS[PlayerData.second_job.name][i].headerTitle, "CreateNewForm", DOCUMENT_FORMS[PlayerData.second_job.name][i])
        end
    end
    Menu.addButton(_U('close_bt'), "CloseMenu", nil)
    Menu.hidden = false
end`

**Comment by TanguyOrtegat** [comment]
what would be better is when you open the job menu you must choose creating it for first or second job and when choosing, it does change on the form too

**Comment by apoiat** [comment]
I appreciate all your aid, really, but sometimes people have to do their own modding. For me to implement a feature like this, it requires to implement functionality that will support both options (meaning single and double jobs), quality test them and make sure they both work flawlessly and in a user-friendly fashion. Seems quite the work so i'm going to skip this one sorry.
