### ISSUE TITLE
cancel button not working

### ISSUE THREAD

**Issue by TanguyOrtegat** [apoiat/ESX_Documents#7]
Cancel button is not working, pressing escape button works for dismissing the document, but on creating a form the cancel button doesn't work

**Comment by apoiat** [comment]
Yes it's decorative still i'll have a look into it and get back. thanks

**Comment by apoiat** [comment]
It has been fixed.

**Comment by TanguyOrtegat** [comment]
i have put it in pull request but okay thanks :)
