### ISSUE TITLE
create a scroll menu

### ISSUE THREAD

**Issue by TanguyOrtegat** [apoiat/ESX_Documents#8]
what would be great is greate a scroll menu on saved documents. Becasue once we got lot's of documents, speaking about cops and so on, players will have a lot of documents and now we cans scroll and the list is out of range of our screen.

**Comment by apoiat** [comment]
True, along with most of your suggestions, already on my to-do list!

**Comment by TanguyOrtegat** [comment]
great to here that!

**Comment by Deniel00** [comment]
+1
